version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydatabase
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
